### ISSUE TITLE
Missing UB leads to a Gurobi Error 10003

### ISSUE THREAD

**Issue by votroto** [jump-dev/PolyJuMP.jl#107]
Running a program without an upper bound
```jl
using JuMP, PolyJuMP, Gurobi, LinearAlgebra

model = Model(() -> PolyJuMP.QCQP.Optimizer(Gurobi.Optimizer()))
@variable(model, 0 <= x)

@objective(model, Min, x^3 )
optimize!(model)
```
throws a bad error
```
ERROR: LoadError: Gurobi Error 10003: Element 0 of a double array is Nan.
```
however given that Gurobi considers bounds above 1e30 as infinite, a simple workaround is to change it to 
```jl
@variable(model, 0 <= x <= 1e31)
```
which should not change the behavior.

## Versions
```
Name            : gurobi
Version         : 11.0.0-2
```

**Comment by odow** [comment]
I assume the problem is that these don't check for `NaN`: 

https://github.com/jump-dev/PolyJuMP.jl/blob/36c4aa284f5e1216ff65dcaf2c7da70663999113/src/QCQP/MOI_wrapper.jl#L266-L271
